apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: label-studio
  annotations:
    konghq.com/strip-path: "true"
    kubernetes.io/ingress.class: nginx
    konghq.com/override: "https-only"
    cert-manager.io/issuer: "letsencrypt-prod-app"
    certmanager.k8s.io/acme-challenge-type: "dns01"
    certmanager.k8s.io/acme-dns01-provider: "digitalocean"
    nginx.ingress.kubernetes.io/auth-url: "https://github-oauth2.app.mesolitica.com/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://github-oauth2.app.mesolitica.com/oauth2/start?rd=$scheme://$host$request_uri"
    nginx.org/client-max-body-size: 1000M
    nginx.ingress.kubernetes.io/proxy-body-size: 1000m
spec:
  tls:
    - hosts:
        - label-studio.app.mesolitica.com
      secretName: wildcard-cert-app
  rules:
    - host: label-studio.app.mesolitica.com
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: label-studio
                port:
                  number: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: label-studio
  labels:
    app: label-studio
spec:
  ports:
    - port: 8080
  clusterIP: None
  selector:
    app: label-studio
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: label-studio
spec:
  selector:
    matchLabels:
      app: label-studio
  serviceName: "label-studio"
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: label-studio
    spec:
      tolerations:
        - key: "kubernetes.azure.com/scalesetpriority"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
        - key: "sku"
          operator: "Equal"
          value: "gpu"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "kubernetes.azure.com/scalesetpriority"
                    operator: In
                    values:
                      - "spot"
                  - key: "agentpool"
                    operator: In
                    values:
                      - "gpu"
      terminationGracePeriodSeconds: 10
      initContainers:
      - name: chmod-container
        image: busybox
        volumeMounts:
            - name: storage
              mountPath: /label-studio/data
        command: ["chmod", "777", "/label-studio/data"]
      containers:
        - name: label-studio
          image: heartexlabs/label-studio:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: storage
              mountPath: /label-studio/data
          env:
            - name: SHELL
              value: "/bin/bash"
            - name: DJANGO_DB
              value: default
            - name: POSTGRE_NAME
              value: postgres
            - name: POSTGRE_USER
              value: postgres
            - name: POSTGRE_PASSWORD
              value: E7lOFx7F4k
            - name: POSTGRE_PORT
              value: "5432"
            - name: POSTGRE_HOST
              value: general-postgresql
            - name: USERNAME
              value: admin
            - name: PASSWORD
              value: admin
          command: ["/bin/bash", "-c"]
          args:
            [
              "label-studio start my_project --init -db postgresql",
            ]

  volumeClaimTemplates:
    - metadata:
        name: storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: default
        resources:
          requests:
            storage: 50Gi