apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpbin-kong-ingress
  annotations:
    konghq.com/strip-path: 'true'
    konghq.com/plugins: 'rate-limit-5-min,key-auth'
spec:
  ingressClassName: kong
  rules:
  - host: httpbin.kong-devtalk.malaysia-ai.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: httpbin-service
            port:
              number: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin-deployment
spec:
  selector:
    matchLabels:
      app: httpbin
  replicas: 1
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      containers:
      - name: httpbin
        image: kennethreitz/httpbin:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin-service
spec:
  selector:
    app: httpbin
  ports:
    - protocol: TCP
      port: 80