apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-example-com
  namespace: traefik
spec:
  secretName: wildcard-example-com-tls
  dnsNames:
    - "devtalk.malaysia-ai.org"
    - "*.devtalk.malaysia-ai.org"
  issuerRef:
    name: cloudflare
    kind: Issuer